POST http://localhost:3001
Content-Type: application/json

{
	"content": "VS code rest is the best",
	"important": true
}
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
	"content": "Ensure that everything still works",
	"important": true
}
